PruebaDeisne/crudProducts/urls.py
from django.contrib import admin  
from django.urls import path , include
from products import views  
from products.api.router import router_products

urlpatterns = [  
    path('admin/', admin.site.urls),
    path('', views.index), 
    path('index', views.index),   
    path('signin', views.signin),
    path('contacto', views.contacto),
    path('carrito', views.carrito),
    path('tienda', views.tienda),
    path('registro', views.registro),
    path('addProduct', views.addProduct),
    path('recupera-password', views.recupera_password),
    path('producto-1', views.producto_1),
    path('producto-2', views.producto_2),
    path('emp',views.emp),  
    path('show',views.show),
    path('product-detail/<int:id>', views.showDetails), 
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
    path('api/', include(router_products.urls))
]  

PruebaDeisne/products/models.py
from django.db import models

# Create your models here.
class Products(models.Model):  
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    tipo_obra = models.TextField(max_length=50)
    artista = models.TextField(max_length=50)
    valor = models.IntegerField()
    descripcion = models.TextField(max_length=50)
    pathImagen = models.TextField(max_length=50)
    codigoProducto = models.IntegerField()
    tecnica = models.TextField(max_length=50)
    otros_detalles = models.TextField(max_length=50)
    dimensiones = models.TextField(max_length=50)
    envio = models.TextField(max_length=50)
    anno = models.IntegerField()
    class Meta:  
        db_table = "products"

PruebaDeisne/products/forms.py
from django import forms  
from products.models import Products  
class ProductsForm(forms.ModelForm):  
    class Meta:  
        model = Products  
        fields = "__all__"

PruebaDeisne/products/api/views.py
from rest_framework.viewsets import ModelViewSet
from products.models import Products
from products.api.serializers import ProductsSerializer

class ProductsApiViewSet(ModelViewSet):
    serializer_class = ProductsSerializer
    queryset = Products.objects.all()

PruebaDeisne/products/views.py
from math import prod
from django.shortcuts import render, redirect  
from products.forms import ProductsForm  
from products.models import Products  

import logging
import sys
# Create your views here.

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler("debug.log"),
        logging.StreamHandler(sys.stdout)
    ]
)

def index(request): 
    return render(request,'index.html')

def signin(request): 
    return render(request,'login.html')

def contacto(request):
    return render(request,'contacto.html')

def carrito(request):
    return render(request,'carrito.html')

def tienda(request):
    productss = Products.objects.all()  
    return render(request,'tienda.html',{'productss':productss})

def registro(request):
    return render(request,'registro.html')

def addProduct(request):
    return render(request,'addProduct.html')    

def recupera_password(request):
    return render(request,'recupera-password.html')       

def producto_1(request):
    return render(request,'producto_1.html')       

def producto_2(request):
    return render(request,'producto_2.html')                        


def emp(request):
    logging.info(request.body)  
    if request.method == "POST":
        logging.info("aca 1") 
        form = ProductsForm(request.POST)
        logging.info(form.is_valid()) 
        if form.is_valid(): 
            try:
                form.save()  
                return redirect('/tienda')  
            except:
                logging.info("error")  
                pass  
    else:  
        form = ProductsForm() 
    return render(request,'index.html',{'form':form})  
def show(request):  
    productss = Products.objects.all()  
    return render(request,"show.html",{'productss':productss})

def showDetails(request, id):  
    products = Products.objects.get(id=id)  
    return render(request,'product-detail.html', {'products':products})  

def edit(request, id):  
    products = Products.objects.get(id=id)  
    return render(request,'edit.html', {'products':products})  
def update(request, id):  
    products = Products.objects.get(id=id)  
    form = ProductsForm(request.POST, instance = products)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'products': products})  
def destroy(request, id):  
    products = Products.objects.get(id=id)  
    products.delete()  
    return redirect("/show")  

PruebaDeisne/products/templates/carrito.html
<!DOCTYPE html>
<html lang="es">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Carrito</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/carrito.css' %}">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">    
    <link href="{% static 'css/tienda-css.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/cards.css' %}">
</head>

<body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/carrito.js' %}"></script>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="index"> <img src="{% static 'img/iconos/logo.png' %}" href="index" alt=""
                    height="44"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="tienda">Tienda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contacto">Contactános</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Opciones
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                </form>
                <a href="#" type="button" class="btn btn-secondary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-cart3" viewBox="0 0 16 16">
                        <path
                            d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z">
                        </path>
                    </svg>
                </a>
                <a href="signin" type="button" class="btn btn-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-person" viewBox="0 0 16 16">
                        <path
                            d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z">
                        </path>
                    </svg>
                    Acceder
                </a>
            </div>
        </div>
    </nav>
    <div class="container mt-5 p-3 rounded cart">
        <div class="row no-gutters">
            <div class="col-md-8">
                <div class="product-details mr-2">
                    <div class="d-flex flex-row align-items-center"><i class="fa fa-long-arrow-left"></i><span
                            class="ml-2">Continuar</span></div>
                    <hr>
                    <h6 class="mb-0">Carrito</h6>
                    <div class="d-flex justify-content-between"><span>3 artículos en tu carrito</span>
                        <div class="d-flex flex-row align-items-center"><span class="text-black-50">Ordenar por:</span>
                            <div class="price ml-2"><span class="mr-1">precio</span><i class="fa fa-angle-down"></i>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex justify-content-between align-items-center mt-3 p-2 items rounded">
                        <div class="d-flex flex-row"><img class="rounded" src="{% static 'img/productos/producto1.jpg' %}" width="40">
                            <div class="ml-2"><span class="font-weight-bold d-block">Kirby al óleo</span><span
                                    class="spec">Óleo en lienzo 80x70 cms</span></div>
                        </div>
                        <div class="d-flex flex-row align-items-center"><span class="d-block">2</span><span
                                class="d-block ml-5 font-weight-bold">$50.000</span><i
                                class="fa fa-trash-o ml-3 text-black-50"></i></div>
                    </div>
                    <div class="d-flex justify-content-between align-items-center mt-3 p-2 items rounded">
                        <div class="d-flex flex-row"><img class="rounded" src="{% static 'img/productos/producto2.1.png' %}"
                                width="40">
                            <div class="ml-2"><span class="font-weight-bold d-block">Natasha</span><span
                                    class="spec">Escultura en bronce sin pedestal 50(L)x43(A)x20(P) cms</span></div>
                        </div>
                        <div class="d-flex flex-row align-items-center"><span class="d-block">1</span><span
                                class="d-block ml-5 font-weight-bold">$150.000</span><i
                                class="fa fa-trash-o ml-3 text-black-50"></i></div>
                    </div>

                </div>
            </div>
            <div class="col-md-4">
                <form id="formCarrito">
                    <div class="payment-info">
                        <div class="d-flex justify-content-between align-items-center"><span>Detalle del pago</span><img
                                class="rounded" src="" width="30"></div><span class="type d-block mt-3 mb-1">Tipo de
                            tarjeta</span><label class="radio"> <input type="radio" name="card" value="payment" checked>
                            <span><img width="30" src="https://img.icons8.com/color/48/000000/mastercard.png" /></span>
                        </label>
                        <label class="radio"> <input type="radio" name="card" value="payment"> <span><img width="30"
                                    src="https://img.icons8.com/officel/48/000000/visa.png" /></span> </label>
                        <label class="radio"> <input type="radio" name="card" value="payment"> <span><img width="30"
                                    src="https://img.icons8.com/ultraviolet/48/000000/amex.png" /></span> </label>
                        <label class="radio"> <input type="radio" name="card" value="payment"> <span><img width="30"
                                    src="https://img.icons8.com/officel/48/000000/paypal.png" /></span> </label>
                        <div>
                            <label class="credit-card-label" for="nombre">Nombre titular tarjeta</label>
                            <input type="text" class="form-control credit-inputs" id="nombre" name="nombre" placeholder="Cristiano Ronaldo" required/>
                        </div>
                        <div>
                            <label class="credit-card-label" for="numT">Número de tarjeta</label>
                            <input type="text" class="form-control credit-inputs" id="numT" name="numT" placeholder="0000 0000 0000 0000" required/>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label class="credit-card-label" for="fecha">Fecha</label>
                                <input type="text" class="form-control credit-inputs" id="fecha" name="fecha" placeholder="12/24" required/>
                            </div>
                            <div class="col-md-6">
                                <label class="credit-card-label" for="cvv" id="cvv">CVV</label>
                                <input type="text" class="form-control credit-inputs" id="cvv" name="cvv" placeholder="342" required/>
                            </div>
                        </div>
                        <hr class="line">
                        <div class="d-flex justify-content-between information">
                            <span>Subtotal</span><span>$350.000</span>
                        </div>
                        <div class="d-flex justify-content-between information"><span>Envío</span><span>$25.000</span>
                        </div>
                        <div class="d-flex justify-content-between information"><span>
                                <h5>Total(Incl.IVA)</h5>
                            </span>
                            <span>
                                <h5>$375.000</h5>
                            </span>
                        </div><button class="btn btn-primary btn-block d-flex justify-content-between mt-3"
                            type="submit"><span>Pagar</span><span><i
                                    class="fa fa-long-arrow-right ml-1"></i></span></button>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <div class="pt-5">
        <footer class="bg-light text-center fixed-bottom">

            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
                © 2022 Copyright:
                <a class="text-dark" href="https://www.duoc.cl/">Deisne INC</a>
            </div>
        </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.4/dist/jquery.validate.js"></script>
</body>

</html>

PruebaDeisne/products/templates/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" href="{% static 'css/cards.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="index"> <img src="{% static 'img/iconos/logo.png' %}" href="index" alt=""
                    height="44"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="tienda">Tienda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contacto">Contactános</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Opciones
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                </form>
                <a href="carrito.html" type="button" class="btn btn-secondary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-cart3" viewBox="0 0 16 16">
                        <path
                            d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z">
                        </path>
                    </svg>
                </a>
                <a href="login" type="button" class="btn btn-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-person" viewBox="0 0 16 16">
                        <path
                            d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z">
                        </path>
                    </svg>
                    Acceder
                </a>
            </div>
        </div>
    </nav><br><br><br>

    <form method="POST" class="post-form" action="/update/{{products.id}}">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Actualizar Detalles Obra</h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Id Producto:</label>
                <div class="col-sm-4">
                    <input type="text" name="id" id="id_id" required maxlength="20" value="{{ products.id }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Nombre Obra:</label>
                <div class="col-sm-4">
                    <input type="text" name="name" id="id_name" required maxlength="100"
                        value="{{ products.name }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Descripción:</label>
                <div class="col-sm-4">
                    <input type="description" name="description" id="id_description" required maxlength="254"
                        value="{{ products.description }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Valor:</label>
                <div class="col-sm-4">
                    <input type="text" name="price" id="id_price" required maxlength="15"
                        value="{{ products.price }}" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success">Actualizar</button>
                </div>
            </div>
        </div>
    </form>

    <div class="pt-5">
        <footer class="bg-light text-center fixed-bottom">

            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
                © 2022 Copyright:
                <a class="text-dark" href="https://www.duoc.cl/">Deisne INC</a>
            </div>
        </footer>
    </div>

</body>

</html>

PruebaDeisne/products/templates/show.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>Products Records</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" href="{% static 'css/cards.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="index"> <img src="{% static 'img/iconos/logo.png' %}" href="index" alt=""
                    height="44"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="tienda">Tienda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contacto">Contactános</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Opciones
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Buscar</button>
                </form>
                <a href="carrito.html" type="button" class="btn btn-secondary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-cart3" viewBox="0 0 16 16">
                        <path
                            d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z">
                        </path>
                    </svg>
                </a>
                <a href="login" type="button" class="btn btn-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-person" viewBox="0 0 16 16">
                        <path
                            d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z">
                        </path>
                    </svg>
                    Acceder
                </a>
            </div>
        </div>
    </nav><br><br><br><br>
    <div>
        <table class="table table-striped table-bordered table-sm">
            <thead class="thead-dark">
                <tr>
                    <th>Folio</th>
                    <th>Código</th>
                    <th>Nombre obra</th>
                    <th>Tipo obra</th>
                    <th>Artista</th>
                    <th>Año</th>
                    <th>Valor</th>
                    <th>Técnica</th>
                    <th>Tipo obra</th>
                    <th>Descripción</th>
                    <th>Otros detalles</th>
                    <th>Dimensiones</th>
                    <th>Envío</th>
                    <th>Ruta imagen</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for products in productss %}
                <tr>
                    <td>{{ products.id }}</td>
                    <td>{{ products.codigoProducto }}</td>
                    <td>{{ products.nombre }}</td>
                    <td>{{ products.tipo_obra }}</td>
                    <td>{{ products.artista }}</td>
                    <td>{{ products.anno }}</td>
                    <td>{{ products.valor }}</td>                  
                    <td>{{ products.tecnica }}</td>
                    <td>{{ products.tipo_obra }}</td>
                    <td>{{ products.descripcion }}</td>
                    <td>{{ products.otros_detalles }}</td>
                    <td>{{ products.dimensiones }}</td>
                    <td>{{ products.envio }}</td>
                    <td>{{ products.pathImagen }}</td>
                    <td>
                        <a href="/edit/{{ products.id }}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
                        <a href="/delete/{{ products.id }}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
        <br>
        <center><a href="/addProduct" class="btn btn-primary">Agregar Nuevo Producto</a></center>
    </div> 
    
    <div class="pt-5">
        <footer class="bg-light text-center fixed-bottom">

            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
                © 2022 Copyright:
                <a class="text-dark" href="https://www.duoc.cl/">Deisne INC</a>
            </div>
        </footer>
    </div>
    
</body>

</html>